### ISSUE TITLE
Would you be able to add Windows 10 enterprise IoT?

### ISSUE THREAD

**Issue by KoleckOLP** [mrrobot1o1/OS-Downloads#1]
Windows 10 IoT Enterprise LTSC 2021 English

**Comment by Regis-Loyaute** [comment]
https://archive.org/details/en-us_windows_10_iot_enterprise_ltsc_2021_x64_dvd_257ad90f_202301

**Comment by mrrobot1o1** [comment]
> Windows 10 IoT Enterprise LTSC 2021 English

We may not have an official download of this edition but I can provide you a download link.  

A trusted source: 

https://haze.seedhost.eu/user/windows/10/ltsc/en-us_windows_10_iot_enterprise_ltsc_2021_x64_dvd_257ad90f.iso

SHA-256: A0334F31EA7A3E6932B9AD7206608248F0BD40698BFB8FC65F14FC5E4976C160

> I will add some unofficial sources very soon.

**Comment by KoleckOLP** [comment]
I found all windows installers here:
https://massgrave.dev/genuine-installation-media.html

**Comment by mrrobot1o1** [comment]
> I found all windows installers here: https://massgrave.dev/genuine-installation-media.html

Wow!!  Great. but I'm not sure all of them are from Microsoft server.

**Comment by KoleckOLP** [comment]
Not all links he provides are from Microsoft Server, neither is archive.org but if you scroll down on the page I send he provided instruction to check the hash of the file you download against genuine windows ISO's from MSDN.
