### ISSUE TITLE
Windows 7 ISOs URL not longer valid

### ISSUE THREAD

**Issue by Dragodraki** [mrrobot1o1/OS-Downloads#2]
Knowing you offer direct links, maybe you'd like to delete Windows ISO links for sources that would have been deleted by Microsoft permanently or use 3rd party links instead. Windows 7 for example cant be downloaded anymore with free public links from MS. Maybe other too, I didn't tested them all.

**Comment by Dragodraki** [comment]
You can delete the issue if you want - it should be more of a reminder than actually a bug report.

**Comment by maydoxx1** [comment]
Hello, Dragon So I found the perfect way to download
here's the updated link:
https://web.archive.org/web/20190313165041/https://download.microsoft.com/download/0/6/3/06365375-C346-4D65-87C7-EE41F55F736B/7601.24214.180801-1700.win7sp1_ldr_escrow_CLIENT_PROFESSIONAL_x64FRE_en-us.iso
don't worry it's safe link i tested before and it's from Microsoft Source but it's archived.

**Comment by mrrobot1o1** [comment]
Thank you, everyone! I have updated the repositories with some reliable links to download the ISOs that are no longer officially available.
