### ISSUE TITLE
Windows 8.1 got taken down

### ISSUE THREAD

**Issue by maydoxx1** [mrrobot1o1/OS-Downloads#3]
Yes it got taken down and redirect to life cycle of windows versions.

**Comment by mrrobot1o1** [comment]
Thank you for raising the issue. I have provided a trusted source not official but somewhat reliable for downloading directly from the provided link.

**Comment by mrrobot1o1** [comment]
Thank you for raising the issue. I have provided a trusted source not official but somewhat reliable for downloading directly from the provided link.
